planning:
  dt: 0.2
  replanning_frequency: 3
  time_steps_computation: 15

vehicle:
  # CR vehicle type (see commonroad-vehicle-models): #1: Ford Escort, #2: BMW 320i, 3 = VW Vanagon
  id_type_vehicle: 2